//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dCForm.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dCForm.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Audit.
        /// </summary>
        public static string ExitAuditText {
            get {
                return ResourceManager.GetString("ExitAuditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No approved form could be found to copy.
        /// </summary>
        public static string FormNotFoundText {
            get {
                return ResourceManager.GetString("FormNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string InfoPathGrid_OnDataBinding_Show {
            get {
                return ResourceManager.GetString("InfoPathGrid_OnDataBinding_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download a new form to fill.
        /// </summary>
        public static string InfoPathPanel__newButton_Download_a_new_form_to_fill {
            get {
                return ResourceManager.GetString("InfoPathPanel__newButton_Download_a_new_form_to_fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was not found.
        ///dCForm requires a custom HTTPHanlder defined declared in this file. Ensure this folder &amp; file exist. Content of the web.config should contain the following:
        ///{1}.
        /// </summary>
        public static string IPB_Relay_Not_Found_Exception_Message {
            get {
                return ResourceManager.GetString("IPB_Relay_Not_Found_Exception_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download a new form to fill.
        /// </summary>
        public static string NewFormText {
            get {
                return ResourceManager.GetString("NewFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Forms Found.
        /// </summary>
        public static string No_Forms_Found {
            get {
                return ResourceManager.GetString("No_Forms_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefilled.
        /// </summary>
        public static string preFillCheckBox_Text {
            get {
                return ResourceManager.GetString("preFillCheckBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer &quot;not required&quot; values from the recently approved submission.
        /// </summary>
        public static string preFillCheckBox_Title {
            get {
                return ResourceManager.GetString("preFillCheckBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to again [y/n&apos;]:.
        /// </summary>
        public static string Program_Main_again__y_n___ {
            get {
                return ResourceManager.GetString("Program_Main_again__y_n___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search all content of forms submitted.
        /// </summary>
        public static string SearchBoxTitle_Text {
            get {
                return ResourceManager.GetString("SearchBoxTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Forms Submitted.
        /// </summary>
        public static string SearchBoxWatermark_Text {
            get {
                return ResourceManager.GetString("SearchBoxWatermark_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start New Form.
        /// </summary>
        public static string textFillOutForm {
            get {
                return ResourceManager.GetString("textFillOutForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download form for editing prefilled with:{0}.
        /// </summary>
        public static string titleFillOutForm {
            get {
                return ResourceManager.GetString("titleFillOutForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///
        ///
        ///
        ///&lt;!-- This configuration &amp; it&apos;s parent directory are an HTTPHandler solution relaying request to a &quot;back-end&quot; dCForm WCF WS &amp; content server --&gt;
        ///&lt;!-- Move this file or changing it&apos;s parent folder&apos;s name will break relaying for dCForm forms --&gt;
        ///
        ///
        ///
        ///&lt;configuration&gt;
        ///  &lt;system.webServer&gt;
        ///    &lt;modules runAllManagedModulesForAllRequests=&quot;true&quot;/&gt;
        ///    &lt;handlers&gt;
        ///      &lt;add
        ///        name=&quot;dCFormRelay_Integrated&quot;
        ///        preCondition=&quot;integratedMode&quot;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        public static string web {
            get {
                return ResourceManager.GetString("web", resourceCulture);
            }
        }
    }
}
